source/backend/controllers/AdminUserController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use backend\models\adminUser\AdminUserForm;
use backend\models\adminUser\AdminUserIndex;
use backend\models\adminUser\AdminUserView;
use backend\models\user\ChangePasswordForm;
use common\models\User;

/**
 * AdminUserController implements the CRUD actions for User model.
 */
class AdminUserController extends \backend\components\Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['sysadmin']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['change-password'],
                        'roles' => ['admin'],
                    ],
                ]
            ],
            'audit' => [
                'class' => \common\components\AuditBehavior::className(),
                'actions' => [
                    'create:POST' => "User {} created",
                    'update:POST' => "User {id} updated",
                    'delete' => "User {id} deleted",
                    'changePassword:POST' => "Changed User {id} password"
                ]
            ],
            'session' => [
                'class' => \common\components\SessionBehavior::className(),
                'actions' => [
                    'index' => [
                        AdminUserView::SESSION_KEY_BACK_URL => Url::current(),
                        AdminUserForm::SESSION_KEY_BACK_URL => Url::current()
                    ],
                    'view' => [
                        AdminUserForm::SESSION_KEY_BACK_URL => Url::current()
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdminUserIndex(['modelObject' => new User()]);
        $dataProvider = $searchModel->search(Yii::$app->request->post());

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'hideSearch' => $searchModel->searchNotEmpty
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findViewModel($id)
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'previous' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AdminUserForm([
            'modelObject' => new User(),
            'scenario' => AdminUserForm::SCENARIO_NEW
        ]);

        return $this->manage($model, Yii::t('admin', 'User created successfully'));
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'previous' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findFormModel($id);

        return $this->manage($model, Yii::t('admin', 'User updated successfully'));
    }

    /**
     * Updates an existing Users password
     * @param $id
     * @return string
     */
    public function actionChangePassword($id)
    {
        $model = new ChangePasswordForm(['modelObject' => $this->findModel($id)]);

        if (Yii::$app->request->isPost && $model->save(Yii::$app->request->post()))
        {
            Yii::$app->session->setFlash('success', Yii::t('admin', 'Password changed successfully'));

            if (Yii::$app->user->id == $id)
            {
                return $this->redirect(["/dashboard"]);
            }

            return $this->redirect($model->getBackUrl());
        } else
        {
            Yii::$app->session->setFlash('error', Yii::t('admin', 'Password not changed successfully. Errors are ' . implode(", ", $model->getErrors()) ));
        }

        return $this->render("change-password", [
                    'model' => $model
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'previous' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findFormModel($id);

        if ($model->delete())
        {
            Yii::$app->session->setFlash('success', Yii::t('admin', 'User deleted successfully'));
        } else
        {
            Yii::$app->session->setFlash('error', Yii::t('admin', 'Cannot delete user'));
        }

        $return = Yii::$app->session->get(
                AdminUserView::SESSION_KEY_BACK_URL, ['/admin-user']
        );
        return $this->redirect($return);
    }

    /**
     * Disable an existing User model.
     * If disable is successful, the browser will be redirected to the 'previous' page.
     * @param string $id
     * @return mixed
     */
    public function actionDisable($id)
    {
        $model = $this->findFormModel($id);
        if ($model->disable())
        {
            Yii::$app->session->setFlash('success', Yii::t('admin', 'User disabled successfully'));
        } else
        {
            Yii::$app->session->setFlash('error', Yii::t('admin', 'Cannot disable user'));
        }


        return $this->redirect($model->getBackUrl());
    }

    /**
     * Enable an existing User model.
     * If enable is successful, the browser will be redirected to the 'previous' page.
     * @param string $id
     * @return mixed
     */
    public function actionEnable($id)
    {
        $model = $this->findFormModel($id);
        if ($model->enable())
        {
            Yii::$app->session->setFlash('success', Yii::t('admin', 'User enabled successfully'));
        } else
        {
            Yii::$app->session->setFlash('error', Yii::t('admin', 'Cannot enable user'));
        }

        return $this->redirect($model->getBackUrl());
    }

    /**
     * Finds the UserView model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return \backend\models\adminUser\AdminUserView the loaded view model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findViewModel($id)
    {
        return new AdminUserView(['modelObject' => User::findOne($id)]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return \backend\models\adminUser\AdminUserForm the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findFormModel($id)
    {
        return new AdminUserForm(['modelObject' => User::findOne($id)]);
    }

    /**
     * Find the User model based on its primary key value
     * @param $id
     * @return \common\models\User
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) != null)
        {
            return $model;
        } else
        {
            throw new NotFoundHttpException(Yii::t('admin', 'The requested page does not exist.'));
        }
    }

    /**
     * Base function handles update/create
     *
     * @param AdminUserForm $model
     * @param $message
     * @return mixed
     */
    private function manage(AdminUserForm $model, $message)
    {
        if (Yii::$app->request->isPost && $model->save(Yii::$app->request->post()))
        {
            Yii::$app->session->setFlash('success', $message);

            return $this->redirect($model->getBackUrl());
        }

        $title = $this->createTitle($model);

        return $this->render('manage', [
                    'model' => $model,
                    'title' => $title
                        ]
        );
    }

    /**
     * Generate page title
     *
     * @param AdminUserForm $formModel
     * @return string
     */
    private function createTitle(AdminUserForm $formModel)
    {
        if ($formModel->modelObject->isNewRecord)
        {
            $title = Yii::t('admin', 'Create User');
        } else
        {
            $title = Yii::t('admin', 'Update User') . ' ' . $formModel->modelObject->id;
        }

        return $title;
    }

}

source/backend/views/admin-user/_form.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\adminUser\AdminUserForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form x_panel">

    <?=
    backend\components\ButtonsHeaderWidget\HeaderWidget::widget([
        'title' => $this->title,
        'showSearch' => false
    ]);
    ?>

    <?php $form = ActiveForm::begin(); ?>

    <div class="user-form x_panel-body">

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            </div>
        </div>


        <?php if ($model->modelObject->isNewRecord) : ?>
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <?= $form->field($model, 'password')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
        <?php endif ?>

        <div class="ln_solid"></div>

    </div>

    <div class="x_panel-footer">
        <div class="form-group">
            <?= $this->render('//site/_back_submit', [
                'backUrl' => $model->getBackUrl()
            ]); ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

source/backend/views/admin-user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\adminUser\AdminUserIndex */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([]); ?>

    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?= $form->field($model, 'username') ?>

        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?= $form->field($model, 'email') ?>

        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?= $form->field($model, 'status_id')->dropDownList($model->getStatusList(), ["prompt" => Yii::t("admin", "Select status")]) ?>

        </div>
    </div>

    <?= $this->render("//site/_search_submit") ?>

    <?php ActiveForm::end(); ?>

</div>

source/backend/views/admin-user/change-password.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\adminUser\AdminUserForm */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('admin', 'Change Password ') . $model->modelObject->username;

?>

<div class="change-password-form x_panel">

    <?= backend\components\ButtonsHeaderWidget\HeaderWidget::widget([
        'title' => $this->title,
        'showSearch' => false
    ]);
    ?>
    
    <?php $form = ActiveForm::begin() ?>

    <div class="user-form x_panel-body">

        <div class="row">
            <div class="col-lg-4">
                <?= $form->field($model, 'password') ?>
            </div>
        </div>
    </div>

    <div class="x_panel-footer">
        <div class="form-group">
            <?= $this->render('//site/_back_submit', [
                'backUrl' => $model->getBackUrl()
            ]); ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

source/backend/views/admin-user/index.php
<?php

use backend\widgets\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\adminUser\AdminUserIndex */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('admin', 'Users');
?>
<div class="user-index x_panel">

    <?= backend\components\ButtonsHeaderWidget\HeaderWidget::widget(
        [
            'title' => $this->title,
            'searchIsEmpty' => $hideSearch,
            'showSearch' => true,
            'buttons' => [
                'create' => [
                    'label' => Yii::t('admin', 'Add  Users')),
                    'class' => 'btn btn-success',
                    'url' => ['create']
                ]
            ]
        ]
    );
    ?>
    <div class="x_panel-body well-lg search <?= $hideSearch ? 'not-important-hidden' : '' ?>">

        <?= $this->render(
            '_search',
            [
                'model' => $searchModel
            ]
        );
        ?>
    </div>

    <div class="x_panel-body">

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'username',
                'email:email',
                'statusLabel',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view}{update}',
                    'headerOptions' => ['class' => 'text-center'],
                    'header' => Yii::t('admin', 'Action'),
                    'buttons' => [
                        'view' => function ($_, $model)
                        {
                            return Html::a('<i class="glyphicon glyphicon-eye-open"></i> &nbsp;' . Yii::t('admin', 'View'), ['admin-user/view', 'id' => $model->id], [
                                'title' => Yii::t('admin', 'View'),
                                'class' => "btn btn-default action-btn btn-xs"
                            ]);
                        },
                        'update' => function ($_, $model)
                        {
                            return Html::a('<i class="glyphicon white glyphicon-pencil"></i> &nbsp;' . Yii::t('admin', 'Update'), ['admin-user/update', 'id' => $model->id], [
                                'title' => Yii::t('admin', 'Update'),
                                'class' => "btn btn-success action-btn btn-xs"
                            ]);
                        }
                    ],
                    'contentOptions' => [
                        'style' => "text-align: center;"
                    ]
                ],
            ]
        ]); ?>
    </div>
</div>

source/backend/views/admin-user/manage.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\adminUser\AdminUserForm */

$this->title = $title;
?>
<div class="user-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

source/backend/views/admin-user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\adminUser\AdminUserView */

$this->title = $model->username;
?>
<div class="user-view x_panel">

    <?=
    backend\components\ButtonsHeaderWidget\HeaderWidget::widget([
        'title' => $this->title,
        'showSearch' => false,
        'buttons' => $model->getButtons()
    ]);
    ?>

    <div class="x_panel-body well-lg">
        <?=
        DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'username',
                'email:email',
                'statusLabel',
                'date_created',
                'date_updated',
                'statusLabel',
                'createdByUsername',
                'updatedByUsername',
            ],
        ])
        ?>

    </div>
</div>