source/common/models/Country.php
<?php

namespace common\models;

use Yii;

/**
 * This is the generated model class for table "country".
 *
 * @property integer $id
 * @property string $name
 * @property integer $invoice_type
 * @property string $currency_label
 * @property string $currency_symbol
 * @property string $booking_price
 * @property integer $status_id
 * @property string $date_created
 * @property string $date_updated
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $is_eu
 * @property integer $is_invoice_payment_allowed
 *
 * @property City[] $cities
 * @property User $createdBy
 * @property Status $status
 * @property User $updatedBy
 * @property CountryPrice[] $countryPrices
 * @property Event[] $events
 * @property ExhibitorProfile[] $exhibitorProfiles
 * @property HostessProfile[] $hostessProfiles
 * @property User[] $users
 * @property CountryMapping[] $sourceMappings
 * @property CountryMapping[] $targetMappings
 * @property HostessCountryMapping[] $hostessCountryMappings
 */
class Country extends \common\components\Model
{

    const INVOICE_EU = 1;
    const INVOICE_DE = 2;
    const INVOCE_OTHER = 3;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'country';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'currency_label', 'currency_symbol', 'booking_price', 'is_eu', 'is_invoice_payment_allowed'], 'required'],
            [['invoice_type', 'status_id', 'created_by', 'updated_by', 'is_eu'], 'integer'],
            [['booking_price'], 'number'],
            [['date_created', 'date_updated'], 'safe'],
            [['name', 'currency_label', 'currency_symbol'], 'filter', 'filter' => '\yii\helpers\HtmlPurifier::process']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array_merge(
                parent::attributeLabels(), [
            'name' => Yii::t('admin', 'Name'),
            'translatedName' => Yii::t('admin', 'Name'),
            'invoice_type' => Yii::t('admin', 'Invoice Type'),
            'currency_label' => Yii::t('admin', 'Currency Label'),
            'currency_symbol' => Yii::t('admin', 'Currency Symbol'),
            'booking_price' => Yii::t('admin', 'Booking Price'),
            'is_eu' => Yii::t('admin', 'Is EU member'),
            'is_invoice_payment_allowed' => Yii::t('admin', 'Is payment on invoice allowed')
                ]
        );
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCities()
    {
        return $this->hasMany(City::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountryPrices()
    {
        return $this->hasMany(CountryPrice::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(Event::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExhibitorProfiles()
    {
        return $this->hasMany(ExhibitorProfile::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHostessProfiles()
    {
        return $this->hasMany(HostessProfile::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTargetMappings()
    {
        return $this->hasMany(CountryMapping::className(), ['target_country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSourceMappings()
    {
        return $this->hasMany(CountryMapping::className(), ['source_country_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHostessCountryMappings()
    {
        return $this->hasMany(HostessCountryMapping::className(), ['country_id' => 'id']);
    }

    /**
     * Get mapped translated list of countries
     * @return array
     */
    public static function getListForDropdown()
    {
        $models = static::find()->all();

        $result = [];
        foreach ($models as $model)
        {
            $result[$model->id] = $model->getTranslatedName();
        }

        asort($result);

        return $result;
    }

    /**
     * Is invoice type Other ( not EU and not Germany )
     * @return boolean
     */
    public function getIsOtherInvoice()
    {
        return $this->invoice_type == static::INVOCE_OTHER;
    }

    /**
     * Is invoice type Germany
     * @return boolean
     */
    public function getIsDeInvoice()
    {
        return $this->invoice_type == static::INVOICE_DE;
    }

    /**
     * Is invoice type EU
     * @return boolean
     */
    public function getIsEuInvoice()
    {
        return $this->invoice_type == static::INVOICE_EU;
    }

    /**
     * Get translated name
     * @return string
     */
    public function getTranslatedName()
    {
        return Yii::t('app.countries', $this->name);
    }

}

source/backend/controllers/CountryController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\helpers\ArrayHelper;
use common\models\Country;
use backend\models\country\CountryView;
use backend\models\country\CountryForm;
use backend\models\country\CountryIndex;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends \backend\components\Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
                    'audit' => [
                        'class' => \common\components\AuditBehavior::className(),
                        'actions' => [
                            'create:POST' => "Country {} created",
                            'update:POST' => "Country {id} updated",
                            'delete' => "Country {id} deleted"
                        ]
                    ],
                    'session' => [
                        'class' => \common\components\SessionBehavior::className(),
                        'actions' => [
                            'index' => [
                                CountryView::SESSION_KEY_BACK_URL => \yii\helpers\Url::current(),
                                CountryForm::SESSION_KEY_BACK_URL => \yii\helpers\Url::current()
                            ],
                            'view' => [
                                CountryForm::SESSION_KEY_BACK_URL => \yii\helpers\Url::current()
                            ]
                        ]
                    ]
        ]);
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CountryIndex(['modelObject' => new Country()]);
        $dataProvider = $searchModel->search(Yii::$app->request->post());

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'hideSearch' => $searchModel->searchNotEmpty
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findViewModel($id),
        ]);
    }

    /**
     * Creates a new Country model.
     * If creation is successful, the browser will be redirected to the 'previous' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CountryForm(['modelObject' => new Country()]);

        return $this->manage($model, Yii::t('admin', 'Country successfully created'));
    }

    /**
     * Updates an existing Country model.
     * If update is successful, the browser will be redirected to the 'previous' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findFormModel($id);

        return $this->manage($model, Yii::t('admin', 'Country successfully updated'));
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'previous' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findFormModel($id);
        if ($model->delete())
        {
            Yii::$app->session->setFlash('success', Yii::t('admin', 'Country successfully deleted'));
        } else
        {
            Yii::$app->session->setFlash('error', Yii::t('admin', 'Country delete failed'));
        }

        $return = Yii::$app->session->get(
                CountryView::SESSION_KEY_BACK_URL, ['/country']
        );
        return $this->redirect($return);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return \backend\models\country\CountryForm the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findFormModel($id)
    {
        return new CountryForm(['modelObject' => $this->findModel($id)]);
    }

    /**
     * Finds the CountryView model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return \backend\models\country\CountryView the loaded view model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findViewModel($id)
    {
        return new CountryView(['modelObject' => $this->findModel($id)]);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return \common\models\Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null)
        {
            return $model;
        } else
        {
            throw new NotFoundHttpException(Yii::t('admin', 'The requested page does not exist.'));
        }
    }

    /**
     * Base function handles update/create
     *
     * @param CountryForm $model
     * @param string $message Flash message to display when successful
     * @return mixed
     */
    private function manage(CountryForm $model, $message)
    {
        if (Yii::$app->request->isPost && $model->save(Yii::$app->request->post()))
        {
            Yii::$app->session->setFlash('success', $message);

            return $this->redirect($model->getBackUrl());
        }

        $title = $this->createTitle($model);

        return $this->render('manage', [
                    'model' => $model,
                    'title' => $title
        ]);
    }

    /**
     * Generate page title
     *
     * @param CountryForm $formModel
     * @return string
     */
    private function createTitle(CountryForm $formModel)
    {
        if ($formModel->modelObject->isNewRecord)
        {
            $title = Yii::t('admin', 'Create Country');
        } else
        {
            $title = Yii::t('admin', 'Update Country') . ' ' . $formModel->modelObject->name;
        }

        return $title;
    }

}

source/backend/views/country/_form.php
<?php

use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model backend\models\country\CountryForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-form x_panel">

    <?=
    backend\components\ButtonsHeaderWidget\HeaderWidget::widget([
        'title' => $this->title,
        'showSearch' => false
    ]);
    ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model) ?>

    <div class="user-form x_panel-body">

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?=
                $form->field($model, 'invoice_type')->widget(Select2::classname(), [
                    'data' => $model->getInvoiceTypesForDropdown(),
                    'options' => ['placeholder' => Yii::t("admin", "Select invoice type")],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'currency_label')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'currency_symbol')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'booking_price')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'is_eu')->checkbox() ?>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <?= $form->field($model, 'is_invoice_payment_allowed')->checkbox() ?>
            </div>
        </div>


    </div>

    <div class="x_panel-footer">
        <div class="form-group">
            <?=
            $this->render('//site/_back_submit', [
                'backUrl' => $model->getBackUrl()
            ]);
            ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

source/backend/views/country/_search.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\country\CountryIndex */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-search">

    <?php
    $form = ActiveForm::begin([
                'action' => ['index'],
    ]);
    ?>

    <div class="row">

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?= $form->field($model, 'name') ?>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?= $form->field($model, 'booking_price') ?>
        </div>

    </div>

    <?= $this->render("//site/_search_submit") ?>

    <?php ActiveForm::end(); ?>

</div>

source/backend/views/country/index.php
<?php

use yii\helpers\Html;
use backend\widgets\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\country\CountryIndex */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('admin', 'Countries');
?>
<div class="country-index x_panel">

    <?=
    backend\components\ButtonsHeaderWidget\HeaderWidget::widget(
            [
                'title' => $this->title,
                'searchIsEmpty' => $hideSearch,
                'showSearch' => true,
                'buttons' => [
                    'create' => [
                        'label' => Yii::t('admin', 'Add  Countries')),
                        'class' => 'btn btn-success',
                        'url' => ['create']
                    ]
                ]
            ]
    );
    ?>
    <div class="x_panel-body well-lg search <?= $hideSearch ? 'not-important-hidden' : '' ?>">

        <?=
        $this->render(
                '_search', [
            'model' => $searchModel
                ]
        );
        ?>
    </div>

    <div class="x_panel-body">

        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'name',
                'booking_price',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view}{update}',
                    'buttons' => [
                        'view' => function ($_, $model)
                        {
                            return Html::a('<i class="glyphicon glyphicon-eye-open"></i> &nbsp;' . Yii::t('admin', 'View'), ['country/view', 'id' => $model->id], [
                                        'title' => Yii::t('admin', 'View'),
                                        'class' => "btn btn-default action-btn btn-xs"
                            ]);
                        },
                                'update' => function ($_, $model)
                        {
                            return Html::a('<i class="glyphicon white glyphicon-pencil"></i> &nbsp;' . Yii::t('admin', 'Update'), ['country/update', 'id' => $model->id], [
                                        'title' => Yii::t('admin', 'Update'),
                                        'class' => "btn btn-success action-btn btn-xs"
                            ]);
                        }
                            ],
                            'contentOptions' => [
                                'style' => "text-align: center;"
                            ]
                        ],
                    ]
                ]);
                ?>
    </div>
</div>

source/backend/views/country/manage.php
<?php
/* @var $this yii\web\View */
/* @var $model backend\models\country\CountryForm */

$this->title = $title;
?>
<div class="country-update">

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

source/backend/views/country/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\country\CountryView */

$this->title = $model->name;
?>
<div class="country-view x_panel">

    <?=
    backend\components\ButtonsHeaderWidget\HeaderWidget::widget([
        'title' => $this->title,
        'showSearch' => false,
        'buttons' => $model->getButtons()
    ]);
    ?>

    <div class="x_panel-body well-lg">
        <?=
        DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'name',
                'isEU',
                'isInvoicePaymentAllowed',
                'invoiceTypeLabel',
                'currency_label',
                'currency_symbol',
                'booking_price',
                'date_created',
                'date_updated',
                'statusLabel',
                'createdByUsername',
                'updatedByUsername',
            ],
        ])
        ?>
    </div>
</div>