source/common/models/Job.php
<?php

namespace common\models;

use Yii;

/**
 * This is the generated model class for table "job".
 *
 * @property integer $id
 * @property string $name
 * @property integer $order
 * @property integer $status_id
 * @property string $date_created
 * @property string $date_updated
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property EventJob[] $eventJobs
 * @property HostessPreferredJob[] $hostessPreferredJobs
 * @property User $createdBy
 * @property Status $status
 * @property User $updatedBy
 * @property RequestJob[] $requestJobs
 */
class Job extends \common\components\Model
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'job';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['order', 'status_id', 'created_by', 'updated_by'], 'integer'],
            [['date_created', 'date_updated'], 'safe'],
            [['name'], 'string', 'max' => 50],
            [['name'], 'filter', 'filter' => '\yii\helpers\HtmlPurifier::process']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array_merge(
                parent::attributeLabels(), [
            'name' => Yii::t('admin', 'Name'),
            'order' => Yii::t('admin', 'Order')
                ]
        );
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventJobs()
    {
        return $this->hasMany(EventJob::className(), ['job_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHostessPreferredJobs()
    {
        return $this->hasMany(HostessPreferredJob::className(), ['event_job_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestJobs()
    {
        return $this->hasMany(RequestJob::className(), ['event_job' => 'id']);
    }

    /**
     * Get translated name
     * @return string
     */
    public function getTranslatedName()
    {
        return Yii::t('app.jobs', $this->name);
    }

}

source/common/models/Request.php
<?php

namespace common\models;

use Yii;

/**
 * This is the generated model class for table "request".
 *
 * @property integer $id
 * @property integer $event_id
 * @property integer $user_id
 * @property integer $requested_user_id
 * @property integer $event_dress_code
 * @property integer $completed
 * @property integer $invoice_id
 * @property integer $status_id
 * @property string $note
 * @property string $date_created
 * @property string $date_from
 * @property string $date_to
 * @property string $date_responded
 * @property decimal $price
 * @property decimal $hostess_original_price
 * @property string $reason
 * @property string $date_rejected
 * @property string $ex_withdraw_reason
 * @property string $ex_withdraw_date
 * @property string $hostess_withdraw_reason
 * @property string $hostess_withdraw_date
 * @property integer $number_of_days
 * @property decimal $booking_price_per_day
 * @property decimal $original_booking_price_per_day
 * @property decimal $total_booking_price
 * @property string  $date_updated
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $days_to_event
 * @property boolean $is_last_minute
 * @property integer $last_minute_percentage
 * @property integer $payment_type
 * @property integer $affiliate_id
 *
 * @property HostessReview[] $hostessReviews
 * @property User $createdBy
 * @property Affiliate $affiliate
 * @property Status $status
 * @property User $updatedBy
 * @property Event $event
 * @property DressCode $eventDressCode
 * @property User $user
 * @property Invoice $invoice
 * @property User $requestedUser
 * @property User $userRequested
 * @property RequestJob[] $requestJobs
 */
class Request extends \common\components\Model
{

    // completion status
    const NOT_COMPLETED = 0;
    const COMPLETED = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'request';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id', 'user_id', 'requested_user_id', 'event_dress_code', 'number_of_days', 'booking_price_per_day', 'total_booking_price', 'price', 'payment_type', 'hostess_original_price', 'original_booking_price_per_day', 'days_to_event', 'is_last_minute', 'last_minute_percentage'], 'required'],
            [['event_id', 'user_id', 'requested_user_id', 'event_dress_code', 'completed', 'invoice_id', 'status_id', 'number_of_days', 'created_by', 'updated_by', 'affiliate_id'], 'integer'],
            [['date_created', 'date_from', 'date_to', 'date_responded', 'date_rejected', 'hostess_withdraw_reason', 'hostess_withdraw_date', 'date_updated'], 'safe'],
            [['booking_price_per_day', 'total_booking_price', 'price'], 'number'],
            [['note'], 'string', 'max' => 50],
            [['reason', 'ex_withdraw_reason', 'ex_withdraw_date'], 'string', 'max' => 255],
            [['note', 'reason', 'ex_withdraw_reason', 'ex_withdraw_date'], 'filter', 'filter' => '\yii\helpers\HtmlPurifier::process'],
            ['date_from', 'compare', 'compareAttribute' => 'date_to', 'operator' => '<=', 'enableClientValidation' => false],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return array_merge(
                parent::attributeLabels(), [
            'event_id' => Yii::t('admin', 'Event'),
            'eventName' => Yii::t('admin', 'Event'),
            'user_id' => Yii::t('admin', 'Hostess'),
            'hostessFullName' => Yii::t('admin', 'Hostess'),
            'hostessEmail' => Yii::t('admin', 'Hostess Email'),
            'hostessPhone' => Yii::t('admin', 'Hostess Phone'),
            'exhibitorFullName' => Yii::t('admin', 'Exhibitor'),
            'exhibitorEmail' => Yii::t('admin', 'Exhibitor Email'),
            'completedDate' => Yii::t('admin', 'Booking date'),
            'requested_user_id' => Yii::t('admin', 'Exhibitor'),
            'event_dress_code' => Yii::t('admin', 'Dress Code'),
            'completed' => Yii::t('admin', 'Completed'),
            'completedLabel' => Yii::t('admin', 'Completed'),
            'invoice_id' => Yii::t('admin', 'Invoice'),
            'status_id' => Yii::t('admin', 'Status'),
            'note' => Yii::t('admin', 'Note'),
            'date_from' => Yii::t('admin', 'Date From'),
            'date_to' => Yii::t('admin', 'Date To'),
            'date_responded' => Yii::t('admin', 'Date Responded'),
            'price' => Yii::t('admin', 'Price'),
            'reason' => Yii::t('admin', 'Reason'),
            'date_rejected' => Yii::t('admin', 'Date Rejected'),
            'ex_withdraw_reason' => Yii::t('admin', 'Exhibitor Withdraw Reason'),
            'ex_withdraw_date' => Yii::t('admin', 'Exhibitor Withdraw Date'),
            'hostess_withdraw_reason' => Yii::t('admin', 'Hostess Withdraw Reason'),
            'hostess_withdraw_date' => Yii::t('admin', 'Hostess Withdraw Date'),
            'number_of_days' => Yii::t('admin', 'Number Of Days'),
            'booking_price_per_day' => Yii::t('admin', 'Booking Price Per Day'),
            'total_booking_price' => Yii::t('admin', 'Total Booking Price'),
            'jobName' => Yii::t('admin', 'Jobs'),
            'normalizedJobName' => Yii::t('admin', 'Jobs'),
            'dressCodeName' => Yii::t('admin', 'Dress Code'),
            'normalizedDressCodeName' => Yii::t('admin', 'Dress Code'),
            'payment_type' => Yii::t('admin', 'Payment of the daily rate'),
            'paymentTypeLabel' => Yii::t('admin', 'Payment of the daily rate'),
            'is_last_minute' => Yii::t('admin', 'Is last minute'),
            'lastMinuteLabel' => Yii::t('admin', 'Is last minute'),
            'affiliateName' => Yii::t('admin', 'Affiliate'),
                ]
        );
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHostessReview()
    {
        return $this->hasOne(HostessReview::className(), ['event_request_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAffiliate()
    {
        return $this->hasOne(Affiliate::className(), ['id' => 'affiliate_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventDressCode()
    {
        return $this->hasOne(DressCode::className(), ['id' => 'event_dress_code']);
    }

    /**
     * For backward compatibility!
     * @return \yii\db\ActiveQuery
     */
    public function getDressCode()
    {
        return $this->getEventDressCode();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(Invoice::className(), ['id' => 'invoice_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestedUser()
    {
        return $this->hasOne(User::className(), ['id' => 'requested_user_id']);
    }

    /**
     * Do not delete. Used for backwards compatibility
     * @return \yii\db\ActiveQuery
     */
    public function getUserRequested()
    {
        return $this->getRequestedUser();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestJobs()
    {
        return $this->hasMany(RequestJob::className(), ['event_request_id' => 'id']);
    }

    /**
     * @return float
     */
    public function calculateBookingPrice()
    {
        return round($this->number_of_days * $this->booking_price_per_day, 2);
    }

    public function calculateBookingDays()
    {
        $zone = new \DateTimeZone('UTC');
        $start = new \DateTime($this->date_from, $zone);
        $end = new \DateTime($this->date_to, $zone);

        $start->setTimeZone($zone);
        $end->setTimeZone($zone);

        $diff = $end->diff($start)->format("%a") + 1;
        return $diff;
    }

    public function getTotalBookingDays()
    {
        return $this->number_of_days;
    }

    public function getIsNew()
    {
        return $this->status_id == Yii::$app->status->request_new;
    }

    public function getIsRejected()
    {
        return $this->status_id == Yii::$app->status->request_reject;
    }

    public function getIsHostessWithdrawAfterAccept()
    {
        return $this->status_id == Yii::$app->status->request_hostess_withdraw_after_accept;
    }

    public function getIsExWithdraw()
    {
        return $this->status_id == Yii::$app->status->request_exhibitor_withdraw;
    }

    public function getIsExWithdrawAfterAccept()
    {
        return $this->status_id == Yii::$app->status->request_exhibitor_withdraw_after_accept;
    }

    public function getIsAccepted()
    {
        return $this->status_id == Yii::$app->status->request_accept;
    }

    public function getIsPaymentPending()
    {
        return $this->status_id == Yii::$app->status->request_paypal_pending;
    }

    /**
     * TODO !!!
     * @return array
     */
    public function getRejectionReasons()
    {
        return [
            "payment_type" => Yii::t('app.hostess', 'Payment of the daily rate'),
            "accepted_different_offer" => Yii::t('app.hostess', 'I have accepted different offer'),

source/frontend/views/hostess-profile/_hostess_images.php
<?php

use yii\helpers\Html;

?>
<ul class="row profile-images">
    <?php if (isset($model->images) && count($model->images) > 0) { ?>
        <?php foreach ($model->images as $image) { ?>
            <li class="col-lg-4">
                <a href="<?= Yii::getAlias("@web") . $image->getImagePath(); ?>" data-fancybox="images">
                    <div class="image img-responsive" style="
                        background-image: url('<?= $image->getCachedImage(53, 75); ?>');
                        ">
                    </div>
                </a>
            </li>
            <?php
        }
    }
    ?>
</ul>

source/frontend/views/hostess-profile/_reject_request_form.php
<?php

use yii\widgets\ActiveForm;
?>

<div>
    <?= Yii::t('app.hostess', 'Request details:') ?>
</div>
<div class="table-responsive">
    <table class="table  table-grey table-bordered text-center">
        <thead>
            <tr class="text-center" style="text-align:center;">
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Event") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', 'Period') ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Days") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Daily rate") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Outfit") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Job") ?></th>
        </thead>
        <tbody>
            <tr>
                <td>
                    <?= $model->event->name ?>
                </td>
                <td>
                    <?= Yii::$app->util->formatDate($model->date_from) . "-" . Yii::$app->util->formatDate($model->date_to) ?>
                </td>
                <td>
                    <?= $model->getTotalBookingDays() ?>
                </td>
                <td>
                    <?= Yii::$app->util->formatPrice($model->price) . " " . Yii::t('app.hostess', 'EUR') ?>
                </td>
                <td>
                    <?= $model->dressCode->translatedName ?>
                </td>
                <td>
                    <?= $model->jobName ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="text-center loading-content">
    <div>
        <?= Yii::t('app.hostess', 'Please wait...') ?>
    </div>
    <br>
    <div class="loader js-loader"></div>    
</div>


<?php
$form = ActiveForm::begin([
            "id" => "reject-request-form",
            "action" => ["/hostess-profile/reject-request", "id" => $model->id]]);


echo $form->field($model, 'reason')
        ->dropDownList($model->getRejectionReasons(), ["prompt" => Yii::t('app.hostess', 'Please select reason')]);

ActiveForm::end();

source/frontend/views/hostess-profile/_reject_request_modal.php
<div class="modal fade" id="reject-request-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog left-aligned">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title"><?= Yii::t('app.hostess', 'Reject request') ?></h3>
            </div>
            <div class="modal-body panel-body" style="min-height: 305px;">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?= Yii::t('app.hostess', 'Cancel') ?>
                </button>
                <button id="options-modal-confirm" type="button" class="btn btn-red  js-btn-confirm-reject">
                    <?= Yii::t('app.hostess', 'Reject') ?>
                </button>
            </div>           
        </div>
    </div>
</div>

source/frontend/views/hostess-profile/_review_item.php
<?php

use kartik\rating\StarRating;
use yii\helpers\Html;

$pluginOptions = [
    'readonly' => true,
    'showClear' => false,
    'showCaption' => false,
    'size' => 'xs'
];
?>


<div class="review-item-content">
    <div class="row border-right">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12">
                    <label class="green-text"> <b>  <?= $model->event->name ?></b></label>
                </div>
            </div>               
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin-top-10">

                    <div class="row">
                        <div class="col-xs-12">
                            <label class="green-text"><?= Yii::t('app.exhibitor', 'Rating') ?></label>
                        </div>
                        <div class="col-xs-12">
                            <?=
                            StarRating::widget([
                                'name' => "rating",
                                'value' => $model->rating,
                                'pluginOptions' => $pluginOptions
                            ]);
                            ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row margin-top-10 comment-section">
                <div class="col-xs-12">
                    <label class="green-text"><?= Yii::t('app.exhibitor', 'Comment') ?></label>
                </div>
                <div class="col-xs-12">
                    <?= $model->comment ?>
                </div>
            </div>
            <div class="row margin-top-10">

                <div class="col-xs-12 text-right">
                    <?= Yii::$app->util->formatDate($model->date_updated) ?>
                </div>                
            </div>

        </div>
    </div>
</div>

source/frontend/views/hostess-profile/_review_modal.php
<div class="modal fade" id="ask-review-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog left-aligned">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title"><?= Yii::t('app.hostess', 'Ask for Review') ?></h3>
            </div>
            <div class="modal-body panel-body" style="min-height: 305px;">

            </div>
            <div class="modal-footer">

                <div class="row">
                    <div class="col-xs-12 text-center">

                        <?= Yii::t('app.hostess', 'Are you sure you want to send review request?') ?>
                    </div>
                </div>

                <br>
                <div class="row">

                    <div class="col-lg-12 text-center">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <?= Yii::t('app.hostess', 'Cancel') ?>
                        </button>
                        <button id="options-modal-confirm" type="button" class="btn btn-green  js-btn-ask-review">
                            <?= Yii::t('app.hostess', "Continue") ?>
                        </button>
                    </div>
                </div>
            </div>           
        </div>
    </div>
</div>

source/frontend/views/hostess-profile/_withdraw_confirmation_form.php
<?php

use yii\widgets\ActiveForm;
?>

<div>
    <?= Yii::t('app.hostess', 'Request details:') ?>
</div>
<div class="table-responsive">
    <table class="table  table-grey table-bordered text-center">
        <thead>
            <tr class="text-center" style="text-align:center;">
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Event") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', 'Period') ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Days") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Daily rate") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Outfit") ?></th>
                <th  style="text-align:center;"><?= Yii::t('app.hostess', "Job") ?></th>
        </thead>
        <tbody>
            <tr>
                <td>
                    <?= $model->event->name ?>
                </td>
                <td>
                    <?= Yii::$app->util->formatDate($model->date_from) . "-" . Yii::$app->util->formatDate($model->date_to) ?>
                </td>
                <td>
                    <?= $model->getTotalBookingDays() ?>
                </td>
                <td>
                    <?= Yii::$app->util->formatPrice($model->price) . " " . Yii::t('app.hostess', 'EUR') ?>
                </td>
                <td>
                    <?= $model->dressCode->translatedName ?>
                </td>
                <td>
                    <?= $model->jobName ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="text-center loading-content">
    <div>
        <?= Yii::t('app.hostess', 'Please wait...') ?>
    </div>
    <br>
    <div class="loader js-loader"></div>    
</div>


<?php
$form = ActiveForm::begin([
            "id" => "withdraw-confirmation-form",
            "action" => ["/hostess-profile/withdraw-confirmation", "id" => $model->id]]);


echo $form->field($model, 'hostess_withdraw_reason')
        ->dropDownList($model->getRejectionReasons(), ["prompt" => Yii::t('app.hostess', 'Please select reason')]);

ActiveForm::end();

source/frontend/views/hostess-profile/_withdraw_confirmation_modal.php
<div class="modal fade" id="withdraw-confirmation-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog left-aligned">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title"><?= Yii::t('app.hostess', 'Withdraw confirmation') ?></h3>
            </div>
            <div class="modal-body panel-body" style="min-height: 305px;">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?= Yii::t('app.hostess', 'Cancel') ?>
                </button>
                <button id="options-modal-confirm" type="button" class="btn btn-red js-btn-withdraw-confirmation">
                    <?= Yii::t('app.hostess', 'Continue') ?>
                </button>
            </div>           
        </div>
    </div>
</div>

source/frontend/views/hostess-profile/current_booking.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

\frontend\assets\HostessProfileAsset::register($this);

$this->title = Yii::t('app.hostess', 'Current Bookings');

$columns = [
    ['class' => 'yii\grid\SerialColumn'],
    [
        'attribute' => 'exhibitor',
        'format' => 'raw',
        'headerOptions' => ['class' => 'text-left'],
        'contentOptions' => ['class' => 'text-left'],
        'header' => Yii::t('app.hostess', "Client"),
        'value' => function ($model, $index, $widget)
{
    return $model->userRequested->fullName . "<br>" . $model->userRequested->email . "<br>" . $model->userRequested->phone_number . "<br>" .
            Html::a($model->userRequested->exhibitorProfile->website, \yii\helpers\Url::to($model->userRequested->exhibitorProfile->website), ['target' => "_blank", "class" => 'green-link']);
},
    ],
    [
        'attribute' => 'event.name',
        'header' => Yii::t('app.hostess', "Event"),
        'format' => 'raw',
        'headerOptions' => ['class' => 'text-left'],
        'contentOptions' => ['class' => 'text-left'],
        'value' => function ($data)
{
    return Html::a(
                    Html::encode($data["event"]["name"]), \Yii::$app->urlManager->createUrl(['//event/view', "id" => $data["event"]["id"]]), ["class" => "green-link bold"]
    );
}
    ],
    [
        'header' => Yii::t('app.hostess', 'Period'),
        'format' => 'raw',
        'value' => function ($model, $index, $widget)
        {
            return Yii::$app->util->formatDate($model->date_from) . "<br>-<br>" . Yii::$app->util->formatDate($model->date_to);
        },
    ],
    [
        'attribute' => 'days',
        'header' => Yii::t('app.hostess', "Days"),
        'value' => function ($model, $index, $widget)
        {
            return $model->getTotalBookingDays();
        }
    ],
    [
        'attribute' => 'daily_rate',
        'header' => Yii::t('app.hostess', "Daily rate"),
        'value' => function($model)
        {
            return Yii::$app->util->formatEventPrice($model->event, $model->price);
        }
    ],
    [
        'attribute' => 'payment_type',
        'header' => Yii::t('app.hostess', "Payment of the daily rate"),
        'value' => function($model)
        {
            return $model->getPaymentTypeLabel();
        }
    ],
    [
        'attribute' => 'dress_code',
        'header' => Yii::t('app.hostess', "Outfit"),
        'value' => function ($model, $index, $widget)
        {
            return $model->dressCode->translatedName;
        },
    ],
    [
        'attribute' => 'job',
        'header' => Yii::t('app.hostess', "Job"),
        'value' => function ($model, $index, $widget)
        {
            return $model->jobName;
        },
    ],
];
?>

        <?= $this->render("profile_parts/_profile_menu", ["model" => $profileModel, "active_tab" => "current_booking"]); ?>
<div class="row hostess-tab-content">
    <div class="col-xs-12">
        <?=
        GridView::widget(
                [
                    'columns' => $columns,
                    'dataProvider' => $dataProvider,
                    'headerRowOptions' => ["class" => "text-center", 'style' => 'text-align:center;'],
                    'options' => [
                        'class' => 'grid-view table-responsive',
                    ],
                    'tableOptions' => [
                        'class' => 'table  table-grey table-bordered',
                    ],
                    'layout' => "{items}",
                ]
        );
        ?>
    </div>
    <div class="col-xs-12 text-right margin-top-20">
        <?php
        echo \yii\widgets\LinkPager::widget([
            'pagination' => $dataProvider->getPagination(),
            'options' => ['class' => 'pagination'],
            'maxButtonCount' => 5,
            'nextPageLabel' => '>',
            'firstPageLabel' => '<<',
            'lastPageLabel' => '>>',
            'prevPageLabel' => '<'
        ]);
        ?>
    </div>  
</div>

source/frontend/views/hostess-profile/reviews.php
<?php
use yii\widgets\ListView;

\frontend\assets\HostessProfileAsset::register($this);


$this->title = Yii::t('app.hostess', 'Reviews');

?>

<?= $this->render("profile_parts/_profile_menu", ["model" => $profileModel, "active_tab" => "reviews"]); ?>
<div class="row hostess-tab-content">

    <div class = "col-lg-12">

        <div class="row">
            <div class="col-xs-12">
                <?php
                echo ListView::widget([
                    'options' => [],
                    'emptyText' => '<div class="text-center">' . Yii::t('app.hostess', 'No ratings available. Customer reviews increase the reliability of your profile up to 10%. You have the possibility to request feedback from your customers in the profile. Go to "Past Bookings" and then "Ask for Review".') . '</div>',
                    'dataProvider' => $dataProvider,
                    'itemOptions' => ['class' => 'margin-top-20 review-item col-lg-6 col-md-6 col-sm-6 col-xs-12'],
                    'layout' => '<div class="row">{items}</div>',
                    'itemView' => function ($model, $key, $index, $widget)
            {

                return $this->render('_review_item', ['model' => $model, 'widget' => $widget]);
            },
                ]);
                ?>  
            </div>
        </div>

        <div class="row text-right margin-top-20">
            <div class="col-xs-12">
                <?php
                echo \yii\widgets\LinkPager::widget([
                    'pagination' => $dataProvider->getPagination(),
                    'options' => ['class' => 'pagination'],
                    'maxButtonCount' => 5,
                    'nextPageLabel' => '>',
                    'firstPageLabel' => '<<',
                    'lastPageLabel' => '>>',
                    'prevPageLabel' => '<'
                ]);
                ?>
            </div>    
        </div>

    </div>
</div>

source/frontend/views/hostess-profile/thankyou.php
<?php
$this->title = Yii::t('app.hostess', 'Thank you');
?>
<div class="banner banner-image registration-hostess">

    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-6 col-xs-12 register-form">
                <div class="row">
                    <div class="col-xs-12 title">
                        <?= Yii::t('app.hostess', 'THANK YOU FOR REGISTERING') ?>
                    </div>
                </div>
                <div class="row margin-top-10">
                    <div class="col-xs-12">
                        <?= Yii::t('app.hostess', 'A verification e-mail has been sent to your e-mail-account (please check the spam inbox too).'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>     
</div>